main/apps/course/urls.py
from django.conf import settings
from django.contrib import admin
from django.views.generic.simple import redirect_to, direct_to_template
from django.conf.urls.defaults import patterns, url, include
from django.contrib.auth import views as auth_views
admin.autodiscover()


urlpatterns = patterns('apps.course.views',
    (r'^(?P<id>.*)$', 'course'),
)

main/urls.py
from django.conf import settings
from django.contrib import admin
from django.views.generic.simple import redirect_to, direct_to_template
from django.conf.urls.defaults import patterns, url, include
from django.contrib.auth import views as auth_views
from apps.college import urls as college_urls
from apps.course import urls as course_urls
from apps.student import urls as student_urls
admin.autodiscover()


urlpatterns = patterns('',
    (r'^favicon.ico$', redirect_to, {'url': '/site_media/static/images/fav.ico'}),
    (r'^robots.txt$', direct_to_template, {'template':'robots.txt', 'mimetype':'text/plain'}),
    (r'^sitemap.txt$', direct_to_template, {'template':'sitemap.txt', 'mimetype':'text/plain'}),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^allCollegeForm$', 'views.allCollegeForm'),
    (r'^coursesWanted$', 'views.coursesWanted'),
    (r'^/$', 'views.home'),
    (r'^$', 'views.home'),
    (r'^schedule/(?P<id>.*)$', 'views.schedule'),
    (r'^colleges/', include(college_urls)),
    (r'^courses/', include(course_urls)),
    (r'^students/', include(student_urls)),
    
)


if settings.DEBUG:
    # let django serve user generated media while in development
    urlpatterns += patterns('',
#TODO don't let people name their top level series admin, site_media, etc.
        (r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

main/apps/college/models.py
from django.db import models
#from django.core.exceptions import ValidationError
#from django.contrib.auth.models import User
#from django.dispatch import receiver 
#from django.db.models.signals import post_save, pre_save
#from django.utils.encoding import smart_str
#from django.contrib.sites.models import Site
from apps.course.models import *
from django.template.defaultfilters import slugify

class College(models.Model):
    name = models.CharField(max_length=200, unique=True)
    abbr = models.CharField(max_length=4, unique=True, null=True, blank=True, default='')
    slug = models.SlugField(null=True, blank=True, default='', editable=False)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ['abbr']
    
    def save(self, *args, **kwargs):
        if self.slug == '':
            self.slug = slugify(self.name)
        super(College, self).save(*args, **kwargs)
        
    @models.permalink
    def get_absolute_url(self):
        return ('apps.college.views.college', [str(self.abbr)])

class Department(models.Model):
    name = models.CharField(max_length=200, unique=True)
    abbr = models.CharField(max_length=4, unique=True, null=True, blank=True, default='')
    slug = models.SlugField(null=True, blank=True, default='', editable=False)
    college = models.ForeignKey(College, null=True, blank=True, default=None)
    courses = models.ManyToManyField(Course, related_name='Courses', null=True, blank=True, default=None)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ['abbr']
    
    def save(self, *args, **kwargs):
        if self.slug == '':
            self.slug = slugify(self.name)
        super(Department, self).save(*args, **kwargs)
    
    @models.permalink
    def get_absolute_url(self):
        return ('apps.college.views.department', [str(self.abbr)])

class Major(models.Model):
    name = models.CharField(max_length=100)
    college = models.ForeignKey(College, null=True, blank=True, default=None)
    department = models.ForeignKey(Department, null=True, blank=True, default=None)
    abbr = models.CharField(max_length=15, null=True, blank=True, default="")
    coursesRequired = models.ManyToManyField(Course, related_name='Required_Course', null=True, blank=True, default=None)
    degree_type = models.CharField(max_length=4, null=True, blank=True, default='')
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ['abbr']
        
    @models.permalink
    def get_absolute_url(self):
        return ('apps.college.views.major', [str(self.abbr)])
    
class Minor(Major):
    pass

main/apps/course/models.py
from django.db import models
#from django.core.exceptions import ValidationError
#from django.contrib.auth.models import User
from django.contrib import admin
#from django.dispatch import receiver 
#from django.db.models.signals import post_save, pre_save
#from django.utils.encoding import smart_str
#from django.contrib.sites.models import Site
from datetime import datetime
import time
from django.contrib.admin.sites import site

WEEKDAYS = (('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'))

class Date(models.Model):
    day = models.CharField(choices=WEEKDAYS, max_length=2, default='', unique=True)
    
    def __unicode__(self):
        return self.day    

class Course(models.Model):
    CLASS_TYPE = (('RES', 'Research'), ('LAB', 'Lab'), ('SEM', 'SEMINAR'), ('',''))
    
    title = models.CharField(max_length=30)
    number = models.IntegerField()
    section_number = models.IntegerField(default=1)
    start_time = models.TimeField(blank=True, null=True)
    end_time = models.TimeField(blank=True, null=True)
    credit_hours = models.IntegerField(default=3)
    time_tba = models.BooleanField(default=False)
    days = models.ManyToManyField(Date, default='')
    building = models.CharField(max_length=50, default='', blank=True, null=True)
    room = models.IntegerField(default=0, blank=True, null=True)
    instructor = models.CharField(max_length=100, default='', blank=True, null=True)
    available_seats = models.IntegerField(default=0, blank=True, null=True)
    number_enrolled = models.IntegerField(default=0, blank=True, null=True)
    special_enrollment = models.CharField(max_length=100, default='', blank=True, null=True)
    type = models.CharField(choices=CLASS_TYPE, max_length=3, default='', null=True, blank=True)
    pretty_days = models.CharField(max_length=10, blank=True, null=True, default='')
    pretty_start = models.CharField(max_length=10, blank=True, null=True, default='')
    pretty_end = models.CharField(max_length=10, blank=True, null=True, default='')
    abbr = models.CharField(max_length=4, blank=True, null=True, default='')
    
    class Meta:
        ordering = ['number']
    
    def __unicode__(self):
        return '%s: %s' % (self.number, self.title)
    
    @models.permalink
    def get_absolute_url(self):
        return ('apps.course.views.course', [str(self.id)])
    
    def get_pretty_days(self):
        days = ""
        for day in self.days.all():
            if day.day == 'H':
                day = "TH"
            days += '%s ' % (day)
        self.pretty_days = days
        return self.pretty_days
    
    def set_pretty_days(self):
        if self.pretty_days == '':
            days = ""
            for day in self.days.all():
                if day.day == 'H':
                    day = "TH"
                days += '%s ' % (day)
            self.pretty_days = days
            self.save()  
              
    def pretty_start_time(self):
        if self.start_time:
            self.pretty_start = self.start_time.strftime("%H:%M")
            return self.pretty_start
    
    def pretty_end_time(self):
        if self.end_time:
            self.pretty_end = self.end_time.strftime("%H:%M")
            return self.pretty_end
    
    def save(self, *args, **kwargs):
        days = ""
        for day in self.days.all():
            if day.day == 'H':
                day = "TH"
            days += '%s ' % (day)
        if self.days:
            self.pretty_days = days.rstrip(' ')
        if self.start_time:
            self.pretty_start = self.start_time.strftime("%H:%M")
        if self.end_time:
            self.pretty_end = self.end_time.strftime("%H:%M")
        super(Course, self).save(*args, **kwargs)
#
#def update_course(modeladmin, request, queryset):
#    queryset.update(status='p')
#update_course.short_description = "Get courses from regex file parsing"
class CourseAdmin(admin.ModelAdmin):
    class Meta:
        model = Course
#   actions = [update_course]
class Lab(models.Model):
    days = models.ManyToManyField(Date, default='', blank=True, null=True)
    building = models.CharField(max_length=50, default='', blank=True, null=True)
    room = models.IntegerField(default=42, blank=True, null=True)
    instructor = models.CharField(max_length=100, default='', blank=True, null=True)
    start_time = models.TimeField(default=datetime.time(datetime.now()), blank=True, null=True)
    end_time = models.TimeField(default=datetime.time(datetime.now()), blank=True, null=True)
    course = models.ForeignKey(Course)
    
    def __unicode__(self):
        return 'LAB %s' % (self.course)
    

main/apps/course/forms.py
from django import forms
from apps.course.models import Course

class CoursesWanted(forms.Form):
    courses = forms.ModelMultipleChoiceField(queryset=Course.objects.all(), required=False)
    student_pk = forms.IntegerField() 

main/apps/course/views.py
from django.conf import settings
from datetime import datetime
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.core.context_processors import csrf
from django.contrib.auth import logout
#from apps.course.models import *
#from apps.student.models import *
from apps.college.models import *
from django.core import serializers
from main.views import common_args
from apps.course.models import WEEKDAYS

def course_args(request):
    args = common_args(request)
    return args

def course(request, id=None):
    if id == None:
        redirect('/courses')
    args = course_args(request)
    args['course'] = serializers.serialize('python', Course.objects.filter(id=id))[0]
    args['weekdays'] = WEEKDAYS
    args.update(csrf(request))
    return render_to_response('course/course.html', args)

templates/course/conflictList.html
<div id='conflictingCourses'>
    {% for course in courses %}
    <li pk='{{ course.id }}'>
    </li>
    {% endfor %}
</div>

templates/course/course.html
{% extends base_template %}
{% block center %} <h3>{{ course.fields.title }}</h3> 
<!-- <h3>{{ weekdays }}</h3> -->
{% for f, v in course.fields.items %}
<li>
	{% if f == "days" %}
		{{f}} : {{ v }}
		<!-- {% for d in v %}
			{{d}},
			{{weekday.d}}
		{% endfor %} -->
	{% else %}
    	{{ f }} : {{ v }}
	{% endif %}	
</li>
{% endfor %}
{% endblock %}

templates/course/courseInfo.html
<h3 class='courseTitle'>{{ course.title }}</h3>
<br>
<h4>Building: </h4><h5 class='building'>{{ course.building }}</h5>
<br>
<h4>Days: </h4><h5 class='days'>{{ course.pretty_days }}</h5><br>
<h4>Instructor: </h4><h5 class='instructor'>{{ course.instructor }}</h5><br>
<h4>Time: </h4><h5 class='time'>{{ course.pretty_start }} - {{ course.pretty_end }}</h5><br>
<h4>Available Seats: </h4><h5 class='available_seats'>{{ course.available_seats }}</h5><br>

templates/course/courseList.html
<div>
    {% for course in courses %}
    <li onclick="possibleClick(this)" onmouseover="displayInfo(this)" pk='{{ course.id }}' class='allCourse' num='{{course.number}}' dept='{{ course.department_set }}' days='{{ course.pretty_days }}' start='{{ course.pretty_start }}' end='{{ course.pretty_end }}' href='{{ course.get_absolute_url }}'>
        {{ course.abbr }} {{ course.number }}
    </li>
    <div class='course-info hidden'>
        {% include 'course/courseInfo.html' with course=course %}
    </div>
    {% endfor %}
</div>

templates/course/scheduleTable.html
<div class='schedule' num="{{ schedule_number }}" id='schedule{{ schedule_number }}' {% if schedule_number != '1'%} style='opacity: 0' {% endif %}>
    <h3>Schedule {{ schedule_number }}</h3>
    <table>
        <tr>
            <th style="border:none;"></th>
            <th>Mon</th>
            <th>Tues</th>
            <th>Wedn</th>
            <th>Thur</th>
            <th>Fri</th>
        </tr>
        {% for i in hours %}
        <tr>
            <th>{{ i }}:00</th>
            <td day='M' time='{{ i }}:00'></td>
            <td day='T' time='{{ i }}:00'></td>
            <td day='W' time='{{ i }}:00'></td>
            <td day='TH' time='{{ i }}:00'></td>
            <td day='F' time='{{ i }}:00'></td>
        </tr>
        <tr>
            <th>{{ i }}:30</th>
            <td day='M' time='{{ i }}:30'></td>
            <td day='T' time='{{ i }}:30'></td>
            <td day='W' time='{{ i }}:30'></td>
            <td day='TH' time='{{ i }}:30'></td>
            <td day='F' time='{{ i }}:30'></td>
        </tr>
        {% endfor %}
    </table>
    <div class='hidden'>
        {% for course in scheduledCourse %}
        <li class='scheduledCourse' pk='{{course.pk}}' num='{{course.number}}' days='{{ course.pretty_days }}' start='{{ course.pretty_start }}' end='{{ course.pretty_end }}' href='{{ course.get_absolute_url }}'>
            {{ course.abbr}} {{ course.number }}
        </li>
        {% endfor %}
    </div>
</div>
{% if schedule_number %}
<div class='scheduleTab' onclick="switchSchedules({{ schedule_number }})" num={{ schedule_number }}>
    <h3>{{ schedule_number }}</h3>
</div>
{% endif %}