main/apps/college/urls.py
from django.conf import settings
from django.contrib import admin
from django.views.generic.simple import redirect_to, direct_to_template
from django.conf.urls.defaults import patterns, url, include
from django.contrib.auth import views as auth_views
admin.autodiscover()


urlpatterns = patterns('apps.college.views',
   (r'^$', 'home'),
   (r'^collegeManager', 'collegeManager'),
   (r'^majorManager', 'majorManager'),
   (r'^department/filter$', 'filter'),
   (r'^department/(?P<abbr>.*)$', 'department'),
   (r'^college/(?P<abbr>.*)$', 'college'),
   (r'^major/(?P<abbr>.*)$', 'major'),
)

main/urls.py
from django.conf import settings
from django.contrib import admin
from django.views.generic.simple import redirect_to, direct_to_template
from django.conf.urls.defaults import patterns, url, include
from django.contrib.auth import views as auth_views
from apps.college import urls as college_urls
from apps.course import urls as course_urls
from apps.student import urls as student_urls
admin.autodiscover()


urlpatterns = patterns('',
    (r'^favicon.ico$', redirect_to, {'url': '/site_media/static/images/fav.ico'}),
    (r'^robots.txt$', direct_to_template, {'template':'robots.txt', 'mimetype':'text/plain'}),
    (r'^sitemap.txt$', direct_to_template, {'template':'sitemap.txt', 'mimetype':'text/plain'}),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^allCollegeForm$', 'views.allCollegeForm'),
    (r'^coursesWanted$', 'views.coursesWanted'),
    (r'^/$', 'views.home'),
    (r'^$', 'views.home'),
    (r'^schedule/(?P<id>.*)$', 'views.schedule'),
    (r'^colleges/', include(college_urls)),
    (r'^courses/', include(course_urls)),
    (r'^students/', include(student_urls)),
    
)


if settings.DEBUG:
    # let django serve user generated media while in development
    urlpatterns += patterns('',
#TODO don't let people name their top level series admin, site_media, etc.
        (r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

main/apps/college/models.py
from django.db import models
#from django.core.exceptions import ValidationError
#from django.contrib.auth.models import User
#from django.dispatch import receiver 
#from django.db.models.signals import post_save, pre_save
#from django.utils.encoding import smart_str
#from django.contrib.sites.models import Site
from apps.course.models import *
from django.template.defaultfilters import slugify

class College(models.Model):
    name = models.CharField(max_length=200, unique=True)
    abbr = models.CharField(max_length=4, unique=True, null=True, blank=True, default='')
    slug = models.SlugField(null=True, blank=True, default='', editable=False)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ['abbr']
    
    def save(self, *args, **kwargs):
        if self.slug == '':
            self.slug = slugify(self.name)
        super(College, self).save(*args, **kwargs)
        
    @models.permalink
    def get_absolute_url(self):
        return ('apps.college.views.college', [str(self.abbr)])

class Department(models.Model):
    name = models.CharField(max_length=200, unique=True)
    abbr = models.CharField(max_length=4, unique=True, null=True, blank=True, default='')
    slug = models.SlugField(null=True, blank=True, default='', editable=False)
    college = models.ForeignKey(College, null=True, blank=True, default=None)
    courses = models.ManyToManyField(Course, related_name='Courses', null=True, blank=True, default=None)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ['abbr']
    
    def save(self, *args, **kwargs):
        if self.slug == '':
            self.slug = slugify(self.name)
        super(Department, self).save(*args, **kwargs)
    
    @models.permalink
    def get_absolute_url(self):
        return ('apps.college.views.department', [str(self.abbr)])

class Major(models.Model):
    name = models.CharField(max_length=100)
    college = models.ForeignKey(College, null=True, blank=True, default=None)
    department = models.ForeignKey(Department, null=True, blank=True, default=None)
    abbr = models.CharField(max_length=15, null=True, blank=True, default="")
    coursesRequired = models.ManyToManyField(Course, related_name='Required_Course', null=True, blank=True, default=None)
    degree_type = models.CharField(max_length=4, null=True, blank=True, default='')
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ['abbr']
        
    @models.permalink
    def get_absolute_url(self):
        return ('apps.college.views.major', [str(self.abbr)])
    
class Minor(Major):
    pass

main/apps/student/models.py
from django.db import models
#from django.core.exceptions import ValidationError
#from django.contrib.auth.models import User
#from django.dispatch import receiver 
#from django.db.models.signals import post_save, pre_save
#from django.utils.encoding import smart_str
#from django.contrib.sites.models import Site
from apps.course.models import *
from apps.college.models import *

class Student(models.Model):
    name = models.CharField(max_length=144, help_text='John Doe')
    id_number = models.IntegerField(default=0, help_text='89#######', null=True, blank=True)
    major = models.ForeignKey(Major)
    minor = models.ForeignKey(Minor, related_name='Minor', null=True, blank=True, default='')
    coursesWanted = models.ManyToManyField(Course, related_name='Wanted_Course', null=True, blank=True, default=None)
    coursesRegistered = models.ManyToManyField(Course, related_name='Registered_Course', null=True, blank=True, default=None)
    coursesNeeded = models.ManyToManyField(Course, related_name='Needed_Course', null=True, blank=True, default=None)
    coursesTaken = models.ManyToManyField(Course, related_name='Taken_Course', null=True, blank=True, default=None)
    
    def __unicode__(self):
        return self.name
        
    class Meta:
        ordering = ['name']
        
    def save(self, *args, **kwargs):
        super(Student, self).save(*args, **kwargs)
        print(self.coursesNeeded.count())
        if self.coursesNeeded.count() < 1:
            self.getCoursesNeeded()

        
    @models.permalink
    def get_absolute_url(self):
        return ('apps.student.views.student', [str(self.id)])
    
    ''' TODO Christian optimize this.
    this should parse the major courses required and check to see if it is in the student needed if not in taken.
    get rid of duplicates in title and number.
    if its in taken, make sure its not in needed.
    '''
    def getCoursesNeeded(self):
        for course in self.major.coursesRequired.all():
            if course not in self.coursesNeeded.all():
                self.coursesNeeded.add(course)
        for course in self.coursesNeeded.all():
            if self.coursesNeeded.filter(number=course.number, title=course.title).count() > 1:
                self.coursesNeeded.remove(course)
        for course in self.coursesTaken.all():
            self.coursesNeeded.remove(course)
        self.save()
        return self.coursesNeeded

main/apps/college/forms.py
from django import forms
from apps.college.models import *

class MajorForm(forms.ModelForm):
    class Meta:
        model = Major

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        
class CollegeManagerForm(forms.Form):
    pk = forms.IntegerField()
    name = forms.CharField()
    abbr = forms.CharField()
    majors = forms.ModelMultipleChoiceField(queryset=Major.objects.all(), required=False)
    departments = forms.ModelMultipleChoiceField(queryset=Department.objects.all(), required=False)
    class Meta:
        model = College

class AllCollegeForm(forms.Form):
    college = forms.ModelMultipleChoiceField(queryset=College.objects.all(), required=False)
    major = forms.ModelMultipleChoiceField(queryset=Major.objects.all(), required=False)
    department = forms.ModelMultipleChoiceField(queryset=Department.objects.all(), required=False)

main/apps/college/views.py
from django.conf import settings
from datetime import datetime
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.core.context_processors import csrf
from django.contrib.auth import logout
#from apps.course.models import *
#from apps.student.models import *
from apps.college.models import *
from apps.college.forms import *
from django.core import serializers
from main.views import common_args

def college_args(request):
    args = common_args(request)
    return args

def home(request):
    args = college_args(request)
    args['departments'] = Department.objects.all()
    args['colleges'] = College.objects.all()
    args['majors'] = Major.objects.all()
    return render_to_response('college/list-all.html', args)

def department(request, abbr=None):
    if abbr == None:
        return redirect('/departments')
    args = college_args(request)
    args['department'] = Department.objects.get(abbr=abbr)
    args.update(csrf(request))
    return render_to_response('college/department.html', args)

def college(request, abbr=None):
    if abbr == None:
        return redirect('/colleges')
    args = college_args(request)
    args['college'] = College.objects.get(abbr=abbr)
    args.update(csrf(request))
    return render_to_response('college/college.html', args)

def major(request, abbr=None):
    if abbr == None:
        return redirect('/majors')
    args = college_args(request)
    args['major'] = Major.objects.get(abbr=abbr)
    args.update(csrf(request))
    return render_to_response('college/major.html', args)

def filter(request, abbr=None):
    args = college_args(request)
    args['departments'] = Department.objects.all()
    args['colleges'] = College.objects.all()
    args['majors'] = Major.objects.all()
    args.update(csrf(request))
    return render_to_response('college/filter.html', args)

def collegeManager(request):
    args = college_args(request)
    if request.method == 'POST':
        print 'its a post'
        print request.POST
        pk = request.POST['pk']
        pk = pk.lstrip(' ')
        college = College.objects.get(id=pk)
        print 'college: %s' % college.name
        form = CollegeManagerForm(request.POST)
        if form.is_valid():
            print 'its valid'
            college.department_set.clear()
            for dept in form.cleaned_data['departments']:
                college.department_set.add(dept)
            college.major_set.clear()
            for maj in form.cleaned_data['majors']:
                print maj
                college.major_set.add(maj)
            college.save()
    args['majorForm'] = MajorForm()
    args['collegeForm'] = CollegeManagerForm()
    args['departmentForm'] = DepartmentForm()
    args['departments'] = Department.objects.all()
    args['colleges'] = College.objects.all()
    args['majors'] = Major.objects.all()
    args.update(csrf(request))
    return render_to_response("college/collegeManager.html", args)

def majorManager(request):
    args = college_args(request)
    if request.method == 'POST':
        print 'its a post'
        print request.POST
        abbr = request.POST['abbr']
        major = Major.objects.get(abbr=abbr)
        form = MajorForm(request.POST, instance=major)
        if form.is_valid():
            form.save()
            print 'its valid'
    args['majorForm'] = MajorForm()
    args['collegeForm'] = CollegeManagerForm()
    args['departmentForm'] = DepartmentForm()
    args['departments'] = Department.objects.all()
    args['colleges'] = College.objects.all()
    args['majors'] = Major.objects.all()
    args['courses'] = Course.objects.all()
    args.update(csrf(request))
    return render_to_response("college/majorManager.html", args)

templates/college/college.html
{% extends base_template %}
{% block center %} 
<h2>{{ college }}</h2>
<div class='column'>
    <h3>Majors</h3>
{% for major in college.major_set.all %} <a href='{{ major.get_absolute_url }}'>
<li>
    {{ major.name }}
</li> </a>
{% endfor %}
</div>

<div class='column'>
    <h3>Departments</h3>
{% for department in college.department_set.all %} <a href='{{ department.get_absolute_url }}'>
<li>
    {{ department.name }}
</li> </a>
{% endfor %}
</div>

{% endblock %}

templates/college/collegeManager.html
{% extends base_template %}
{% block center %}
<style>
    .neededCourse {
        margin: 2px;
    }
    .neededCourse:hover {
        cursor: pointer;
    }
    .hidden {
        display: none;
    }
    #saveMenu {
        position: fixed;
        top: 120px;
        left: 30px;
    }
</style>
<script type='text/javascript'>
    var college = null;
    $(document).ready(function() {
        $('.college').click(function() {
            if(college) {
                if(college == this) {
                    $('#id_name').val('');
                    $('#id_abbr').val('');
                    $("#id_pk").val('');
                    $(this).animate({
                        opacity : 1
                    }, 300);
                    college = null;
                } else {
                    $(college).animate({
                        opacity : 1
                    }, 300);
                    college = this;
                    $('#id_name').val($(college).attr('name'));
                    $('#id_abbr').val($(college).attr('abbr'));
                    $('#id_pk').val($(college).attr('pk'));
                    $(this).animate({
                        opacity : .3
                    }, 300);
                }
            } else {
                college = this;
                $('#id_name').val($(college).attr('name'));
                $('#id_abbr').val($(college).attr('abbr'));
                $('#id_pk').val($(college).attr('pk'));
                $(this).animate({
                    opacity : .3
                }, 300);
            }
            $('p:not(.college)').animate({
                opacity : 1
            }, 300);
            $('option[selected=selected]').removeAttr('selected');
            //Init the department list with the colleges current departments
            $($(college).parent().children('.departments')).children('option').each(function() {
                var me = this;
                console.log(me);
                var p = $('.department[pk=' + $(me).val() + ']');
                var option = $('#id_departments option[value=' + $(me).val() + ']');
                if($(me).attr('selected') == 'selected') {
                    $(option).attr('selected', 'selected');
                    $(p).animate({
                        opacity : .3
                    }, 300);
                } else {
                    $(option).removeAttr('selected');
                    $(p).animate({
                        opacity : 1
                    }, 300);
                }
            });
            //Init the major list with the colleges current majors
            $($(college).parent().children('.majors')).children('option').each(function() {
                var me = this;
                var p = $('.major[pk=' + $(this).val() + ']');
                var option = $('#id_majors option[value=' + $(me).val() + ']');
                if($(me).attr('selected') == 'selected') {
                    $(option).attr('selected', 'selected');
                    $(p).animate({
                        opacity : .3
                    }, 300);
                } else {
                    $(option).removeAttr('selected');
                    $(p).animate({
                        opacity : 1
                    }, 300);
                }
            });
            console.log($(college));
        });
        $('.major').click(function() {
            var me = this;
            if(college == null) {
                alert("Select a college first!");
                return;
            }
            console.log($(me));
            var option = $('#id_majors option[value=' + $(me).attr('pk') + ']');
            option = option[0];
            if($(option).attr('selected') == 'selected') {
                $(option).removeAttr('selected');
                $(me).animate({
                    opacity : 1
                }, 300);
            } else {
                $(option).attr('selected', 'selected');
                $(me).animate({
                    opacity : .3
                }, 300);
            }
        });
        $('.department').click(function() {
            var me = this;
            if(college == null) {
                alert("Select a college first!");
                return;
            }
            console.log(me);
            var option = $('#id_departments option[value=' + $(me).attr('pk') + ']');
            option = option[0];
            if($(option).attr('selected') == 'selected') {
                $(option).removeAttr('selected');
                $(me).animate({
                    opacity : 1
                }, 300);
            } else {
                $(option).attr('selected', 'selected');
                $(me).animate({
                    opacity : .3
                }, 300);
            }
        });
        $("#save").click(function() {
            $.post(window.location, $('#collegeForm').serialize(), function(data) {
                $('html').html(data);
            });
        });
    }); 
</script>
<h3>{{ student.name }}</h3>
<div class='column'>
    <h4> Colleges </h4>
    <p style='font-style: italic;'>
        Select a college to add majors to it
    </p>
    {% for college in colleges.all %}
    <div>
        <p class='college' name='{{ college.name }}' abbr='{{ college.abbr }}' pk='{{ college.id }}'>
            {{ college }}
        </p>
        <div class='hidden majors'>
            {% for major in college.major_set.all %}
            <option value='{{ major.id }}' selected='selected'>{{ major }}</option>
            {% endfor %}
        </div>
        <div class='hidden departments'>
            {% for department in college.department_set.all %}
            <option value='{{ department.id }}' selected='selected'>{{ department }}</option>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
</div>
<div class='column'>
    <h4> Majors </h4>
    <p style='font-style: italic;'>
        Click to indicate this major if part of the selected college
    </p>
    {% for major in majors.all %}
    <p class='major' pk='{{ major.id }}'>
        {{ major }}
    </p>
    {% endfor %}
</div>
<div class='column'>
    <h4> Departments </h4>
    <p style='font-style: italic;'>
        Click to indicate this department if part of the selected college
    </p>
    {% for department in departments.all %}
    <p class='department' pk='{{ department.id }}'>
        {{ department }}
    </p>
    {% endfor %}
</div>
<div class='hidden'>
    <form id='collegeForm' action='' method='POST'>
        {% csrf_token %}
        {{ collegeForm }}
    </form>
</div>
<div id='saveMenu'>
    <button id='save'>
        <h3>save</h3>
    </button>
</div>
{% endblock %} 

templates/college/department.html
{% extends base_template %}
{% block center %} <h3>{{ department }}</h3>
<a href="filter"><h4>Filter List</h4></a>
{% for course in department.courses.all %} <a href='{{ course.get_absolute_url }}'>
<li>
    {{ course.title }}
</li> </a>
{% endfor %}
{% endblock %}

templates/college/departments.html
{% extends base_template %}
{% block center %} <h3>departments</h3>
{% for department in departments %} <a href='{{ department.get_absolute_url }}'>
<li>
    {{ department.name }}
</li> </a>
{% endfor %}
{% endblock %}

templates/college/filter.html
{% extends base_template %}
<style>
    .college {
        margin: 2px;
    }
    .department {
        cursor: pointer;
    }
    .hidden {
        display: none;
    }
    #saveMenu {
        position: fixed;
        top: 120px;
        left: 30px;
    }
</style>
<script type="text/javascript" >
	 $(document).ready(function() {
        $('.neededCourse').click(function() {
            console.log($(this));
            $('#id_coursesNeeded option[value=' + $(this).attr('pk') + ']').attr('selected', '');
            $('#id_coursesTaken option[value=' + $(this).attr('pk') + ']').attr('selected', 'selected');
            $(this).animate({
                opacity : .3
            }, 300);
        });
        $('.takenCourse').click(function() {
            console.log($(this));
            $('#id_coursesNeeded option[value=' + $(this).attr('pk') + ']').attr('selected', 'selected');
            $('#id_coursesTaken option[value=' + $(this).attr('pk') + ']').attr('selected', '');
            $(this).animate({
                opacity : .3
            }, 300);
        });
        $('.allCourse').click(function() {
            console.log($(this));
            $('#id_coursesNeeded option[value=' + $(this).attr('pk') + ']').attr('selected', 'selected');
            $(this).animate({
                opacity : .3
            }, 300);
        });
        $("#save").click(function() {
            $('#studentForm').submit();
        });
    });
</script>
{% block center %} <h3>{{department}} Filter Courses</h3>
<select id="collegeSelect"> 
	{% for college in colleges %}
	<option> 
		<p>{{college.name}}</p>
	</option>
	{% endfor %} 
</select> 
<select id="departmentSelect"> 
	{% for department in departments %}
	<option> 
		<p>{{department.abbr}}</p>
	</option>
	{% endfor %} 
</select> 
<select id="majorSelect"> 
	{% for major in majors %}
	<option> 
		<p>{{major.name}}</p>
	</option>
	{% endfor %} 
</select> 
{% endblock %}

templates/college/list-all.html
{% extends base_template %}
{% block center %}
<style>
.column{
    width: 300px;
    float: left;
}
</style>
<div class='column'>
    <h3>Colleges</h3>
{% for college in colleges %} <a href='{{ college.get_absolute_url }}'>
<li>
    {{ college.name }}
</li> </a>
{% endfor %}
</div>
<div class='column'>
<h3>Majors</h3>
{% for major in majors %} <a href='{{ major.get_absolute_url }}'>
<li>
    {{ major.name }}
</li> </a>
{% endfor %}
</div>
<div class='column'>
<h3>Departments</h3>
{% for department in departments %} <a href='{{ department.get_absolute_url }}'>
<li>
    {{ department.name }}
</li> </a>
{% endfor %}
</div>
{% endblock %}

templates/college/major.html
{% extends base_template %}
{% block center %} <h3>{{ major }}</h3>
<p>
    degree type: {{ major.degree_type }}
</p>
<div class='column'>
    <a href='{{ major.college.get_absolute_url }}'>
    <li>
        College : {{ major.college }}
    </li> </a>
    {% if major.department %}
    <a href='{{ major.department.get_absolute_url }}'>
    <li>
        Department : {{ major.department }}
    </li> </a>
    {% endif %}
</div>
<div class='column'>
    {% for course in major.coursesRequired.all %}
    <a href='{{ course.get_absolute_url }}'>
    <li>
        {{ course.title }}
    </li> {% endfor %}
</div>
{% endblock %}

templates/college/majorManager.html
{% extends base_template %}
{% block center %}
<style>
    .neededCourse {
        margin: 2px;
    }
    .neededCourse:hover {
        cursor: pointer;
    }
    .hidden {
        display: none;
    }
    #saveMenu {
        position: fixed;
        top: 120px;
        left: 30px;
    }
</style>
<script type='text/javascript'>
    var major = null;
    $(document).ready(function() {
        $('.major').click(function() {
            if(major) {
                if(major == this) {
                    $('#id_name').val('');
                    $('#id_abbr').val('');
                    $("#id_pk").val('');
                    $('#id_degree_type').val('');
                    $(major).animate({
                        opacity : 1
                    }, 300);
                    major = null;
                } else {
                    $(major).animate({
                        opacity : 1
                    }, 300);
                    major = this;
                    $('#id_name').val($(major).attr('name'));
                    $('#id_abbr').val($(major).attr('abbr'));
                    $('#id_pk').val($(major).attr('pk'));
                    $('#id_degree_type').val($(major).attr('degree_type'));
                    $(major).animate({
                        opacity : .3
                    }, 300);
                }
            } else {
                major = this;
                $('#id_name').val($(major).attr('name'));
                $('#id_abbr').val($(major).attr('abbr'));
                $('#id_pk').val($(major).attr('pk'));
                $('#id_degree_type').val($(major).attr('degree_type'));
                $(major).animate({
                    opacity : .3
                }, 300);
            }
            $('p:not(.major)').animate({
                opacity : 1
            }, 300);
            $('option[selected=selected]').removeAttr('selected');
            //Init the coursesRequired list with the major's current coursesRequired
            $($(major).siblings('.courses')[0]).children('option').each(function() {
                var me = this;
                var p = $('.course[pk=' + $(me).val() + ']');
                console.log(me);
                var option = $('#id_coursesRequired option[value=' + $(me).val() + ']');
                $(option).attr('selected', 'selected');
                $(p).animate({
                    opacity : .3
                }, 300);
            });
            //Init the college for selected major
            if($($(major).siblings('.collegeM')[0]).children('option')){
                var me = $($(major).siblings('.collegeM')[0]).children('option');
                var option = $('#id_college option[value=' + $(me).val() + ']');
                var p = $('.college[pk=' + $(me).val() + ']');
                console.log(me);
                console.log(option);
                $(option).attr('selected', 'selected');
                $(p).animate({
                    opacity : .3
                }, 300);
            }
            //Init the department for selected major
            if($($(major).siblings('.departmentM')[0]).children('option')){
                var me = $($(major).siblings('.departmentM')[0]).children('option');
                var option = $('#id_department option[value=' + $(me).val() + ']');
                var p = $('.department[pk=' + $(me).val() + ']');
                $(option).attr('selected', 'selected');
                $(p).animate({
                    opacity : .3
                }, 300);
            }
            console.log($(major));
        });
        $('.course').click(function() {
            var me = this;
            if(major == null) {
                alert("Select a major first!");
                return;
            }
            console.log($(me));
            var option = $('#id_coursesRequired option[value=' + $(me).attr('pk') + ']');
            option = option[0];
            console.log(option);
            if($(option).attr('selected') == 'selected') {
                $(option).removeAttr('selected');
                $(me).animate({
                    opacity : 1
                }, 300);
            } else {
                $(option).attr('selected', 'selected');
                $(me).animate({
                    opacity : .3
                }, 300);
            }
        });
        $('.college').click(function() {
            var me = this;
            if(major == null) {
                alert("Select a major first!");
                return;
            }
            console.log(me);
            var option = $('#id_college option[value=' + $(me).attr('pk') + ']');
            option = option[0];
            console.log(option);
            if($(option).attr('selected') == 'selected') {
                $(option).removeAttr('selected');
                $(me).animate({
                    opacity : 1
                }, 300);
            } else {
                $('#id_college option[selected=selected]').removeAttr('selected');
                $(option).attr('selected', 'selected');
                $(me).animate({
                    opacity : .3
                }, 300);
            }
        });
        $('.department').click(function() {
            var me = this;
            if(major == null) {
                alert("Select a major first!");
                return;
            }
            console.log(me);
            var option = $('#id_department option[value=' + $(me).attr('pk') + ']');
            option = option[0];
            console.log(option);
            if($(option).attr('selected') == 'selected') {
                $(option).removeAttr('selected');
                $(me).animate({
                    opacity : 1
                }, 300);
            } else {
                $('#id_department option[selected=selected]').removeAttr('selected');
                $(option).attr('selected', 'selected');
                $(me).animate({
                    opacity : .3
                }, 300);
            }
        });
        $("#save").click(function() {
            $.post(window.location, $('#majorForm').serialize(), function(data) {
                $('html').html(data);
            });
        });
    }); 
</script>
<h3>{{ student.name }}</h3>
<div class='column'>
    <h4> Majors </h4>
    <p style='font-style: italic;'>
        Select a major to manage its college, department, and courses required
    </p>
    {% for major in majors.all %}
    <div>
    <p class='major' degree_type='{{ major.degree_type }}' name='{{ major.name }}' abbr='{{ major.abbr }}' pk='{{ major.id }}'>
        {{ major }}
        <div class='hidden courses'>
            {% for course in major.coursesRequired.all %}
                <option value='{{ course.id }}' selected='selected'>{{ course }}</option>
            {% endfor %}
        </div>
        <div class='hidden departmentM'>
            <option value='{{ major.department.id }}' selected='selected'>{{ major.department }}</option>
        </div>
        <div class='hidden collegeM'>
            <option value='{{ major.college.id }}' selected='selected'>{{ major.college }}</option>
        </div>
    </p>
    </div>
    {% endfor %}
</div>
<div class='column'>
    <h4> Colleges </h4>
    <p style='font-style: italic;'>
        Click to indicate this major if part of the college
    </p>
    {% for college in colleges.all %}
    <p class='college' pk='{{ college.id }}'>
        {{ college }}
    </p>
    {% endfor %}
</div>
<div class='column'>
    <h4> Departments </h4>
    <p style='font-style: italic;'>
        Click to indicate this major if part of the department
    </p>
    {% for department in departments.all %}
    <p class='department' pk='{{ department.id }}'>
        {{ department }}
    </p>
    {% endfor %}
</div>
<div class='column'>
    <h4> Courses Required </h4>
    <p style='font-style: italic;'>
        Click to indicate this course is required of the major
    </p>
    {% for course in courses.all %}
    <p class='course' pk='{{ course.id }}'>
        {{ course }}
    </p>
    {% endfor %}
</div>
<div class='hidden'>
    <form id='majorForm' action='' method='POST'>
        {% csrf_token %}
        {{ majorForm }}
    </form>
</div>
<div id='saveMenu'>
    <button id='save'>
        <h3>save</h3>
    </button>
</div>
{% endblock %} 